name: Build ZMK Firmware

on: [push, pull_request, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
          
      - uses: zmkfirmware/zmk-build-action@v0.1.0
        with:
          board: nrfmicro_1_1    # Matches your HOLYIOT/nRF52840 board
          shield: romac          # Your 4-key macropad shield (will work with 2 keys)
